# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadpicture',
            name='choose',
            field=models.IntegerField(choices=[(1, 'Kishi ucun'), (2, 'Qadin ucun'), (3, 'Ushaq ucun')], default=1),
        ),
        migrations.AlterField(
            model_name='uploadpicture',
            name='price',
            field=models.IntegerField(),
        ),
    ]
