# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_uploadpicture_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadpicture',
            name='author',
        ),
    ]
