# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20170826_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadpicture',
            name='post_image',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='post_image/'),
        ),
    ]
