# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_uploadpicture_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadpicture',
            name='madein',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
