# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 15:05
from __future__ import unicode_literals

from django.db import migrations
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_uploadpicture_madein'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadpicture',
            name='star',
            field=items.models.IntegerRangeField(blank=True, null=True),
        ),
    ]
