# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
